[project]
name = 'Neurotech-Data-Marketplace'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.access-control]
path = 'contracts/access-control.clar'
clarity_version = 2
epoch = 2.5

[contracts.bci-data]
path = 'contracts/bci-data.clar'
clarity_version = 2
epoch = 2.5

[contracts.neuroethics-compliance]
path = 'contracts/neuroethics-compliance.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
